2025-09-24 05:12:24,875 -User: jason21 - Path: /
2025-09-24 05:12:32,971 -User: jason21 - Path: /api-auth/logout/
2025-09-24 05:12:33,016 -User: Anonymous - Path: /
2025-09-24 05:12:33,029 -Unauthorized: /
2025-09-24 05:12:35,000 -User: Anonymous - Path: /api-auth/login/
2025-09-24 05:12:39,107 -User: Anonymous - Path: /api-auth/login/
2025-09-24 05:12:41,275 -User: jason21 - Path: /
2025-09-24 05:12:52,128 -User: jason21 - Path: /messages/
2025-09-24 05:14:01,848 -User: jason21 - Path: /conversation/
2025-09-24 08:51:21,329 -User: jason21 - Path: /
2025-09-24 08:51:28,316 -User: jason21 - Path: /conversation/
2025-09-24 08:51:50,009 -User: jason21 - Path: /messages/
2025-09-24 08:58:15,292 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\views.py changed, reloading.
2025-09-24 08:58:31,563 -User: jason21 - Path: /messages/
2025-09-24 09:02:00,222 -User: jason21 - Path: /
2025-09-24 09:02:05,205 -User: jason21 - Path: /conversation/
2025-09-24 09:02:13,123 -User: jason21 - Path: /messages/
2025-09-24 09:02:53,178 -User: jason21 - Path: /
2025-09-24 09:02:58,973 -User: jason21 - Path: /messages/
2025-09-24 09:08:34,641 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\views.py changed, reloading.
2025-09-24 09:09:04,644 -User: jason21 - Path: /messages/
2025-09-24 09:09:32,274 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\views.py changed, reloading.
2025-09-24 09:09:41,220 -User: jason21 - Path: /messages/
2025-09-24 09:10:32,963 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\views.py changed, reloading.
2025-09-24 09:11:51,461 -User: jason21 - Path: /
2025-09-24 09:11:54,963 -User: jason21 - Path: /messages/
2025-09-24 09:12:42,539 -User: jason21 - Path: /messages/
2025-09-24 09:16:15,172 -User: Anonymous - Path: /api/messages/
2025-09-24 09:16:15,418 -Not Found: /api/messages/
2025-09-24 09:16:28,291 -User: Anonymous - Path: /messages/
2025-09-24 09:18:19,838 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-24 09:20:09,967 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-24 09:21:21,874 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-24 09:21:38,040 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-24 09:21:59,227 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-24 09:23:53,029 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\messaging_app\settings.py changed, reloading.
2025-09-24 09:24:34,014 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-24 11:10:34,895 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-24 11:12:26,032 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-24 11:45:38,895 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-24 11:46:20,857 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-24 11:47:13,953 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-24 11:47:35,387 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-24 11:51:30,173 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-27 16:15:37,935 -User: jason21 - Path: /
2025-09-27 16:15:38,463 -Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\allauth\account\middleware.py", line 34, in middleware
    if _should_redirect_accounts(request, response):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\allauth\account\middleware.py", line 63, in _should_redirect_accounts
    if response.status_code != 404:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'status_code'
2025-09-27 16:15:39,403 -User: jason21 - Path: /favicon.ico
2025-09-27 16:15:39,443 -Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\allauth\account\middleware.py", line 34, in middleware
    if _should_redirect_accounts(request, response):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\allauth\account\middleware.py", line 63, in _should_redirect_accounts
    if response.status_code != 404:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'status_code'
2025-09-27 16:18:34,952 -User: jason21 - Path: /
2025-09-27 16:18:35,078 -Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\allauth\account\middleware.py", line 34, in middleware
    if _should_redirect_accounts(request, response):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\allauth\account\middleware.py", line 63, in _should_redirect_accounts
    if response.status_code != 404:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'status_code'
2025-09-27 16:18:36,040 -User: jason21 - Path: /favicon.ico
2025-09-27 16:18:36,084 -Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\allauth\account\middleware.py", line 34, in middleware
    if _should_redirect_accounts(request, response):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\allauth\account\middleware.py", line 63, in _should_redirect_accounts
    if response.status_code != 404:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'status_code'
2025-09-27 16:20:58,582 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\messaging_app\settings.py changed, reloading.
2025-09-27 16:23:29,945 -User: jason21 - Path: /
2025-09-27 16:23:30,029 -Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\allauth\account\middleware.py", line 34, in middleware
    if _should_redirect_accounts(request, response):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\allauth\account\middleware.py", line 63, in _should_redirect_accounts
    if response.status_code != 404:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'status_code'
2025-09-27 16:23:31,270 -User: jason21 - Path: /favicon.ico
2025-09-27 16:23:31,324 -Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\allauth\account\middleware.py", line 34, in middleware
    if _should_redirect_accounts(request, response):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\allauth\account\middleware.py", line 63, in _should_redirect_accounts
    if response.status_code != 404:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'status_code'
2025-09-27 16:24:26,248 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-27 16:24:35,573 -User: jason21 - Path: /
2025-09-27 16:24:35,725 -Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\allauth\account\middleware.py", line 34, in middleware
    if _should_redirect_accounts(request, response):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\allauth\account\middleware.py", line 63, in _should_redirect_accounts
    if response.status_code != 404:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'status_code'
2025-09-27 16:24:36,927 -User: jason21 - Path: /favicon.ico
2025-09-27 16:24:36,976 -Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\allauth\account\middleware.py", line 34, in middleware
    if _should_redirect_accounts(request, response):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\allauth\account\middleware.py", line 63, in _should_redirect_accounts
    if response.status_code != 404:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'status_code'
2025-09-27 16:24:54,025 -User: jason21 - Path: /
2025-09-27 16:24:54,132 -Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\allauth\account\middleware.py", line 34, in middleware
    if _should_redirect_accounts(request, response):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\allauth\account\middleware.py", line 63, in _should_redirect_accounts
    if response.status_code != 404:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'status_code'
2025-09-27 16:24:55,050 -User: jason21 - Path: /favicon.ico
2025-09-27 16:24:55,099 -Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\allauth\account\middleware.py", line 34, in middleware
    if _should_redirect_accounts(request, response):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\allauth\account\middleware.py", line 63, in _should_redirect_accounts
    if response.status_code != 404:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'status_code'
2025-09-27 16:25:47,032 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-27 16:27:02,505 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\messaging_app\settings.py changed, reloading.
2025-09-27 16:27:13,525 -User: jason21 - Path: /
2025-09-27 16:27:14,774 -User: jason21 - Path: /favicon.ico
2025-09-27 16:27:14,830 -Not Found: /favicon.ico
2025-09-27 16:27:24,343 -User: jason21 - Path: /
2025-09-27 16:27:29,467 -User: jason21 - Path: /
2025-09-27 16:27:37,623 -User: jason21 - Path: /
2025-09-27 16:27:43,427 -User: jason21 - Path: /messages/
2025-09-27 16:27:43,647 -Internal Server Error: /messages/
Traceback (most recent call last):
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py", line 53, in __call__
    fith_message = messages[4]
                   ~~~~~~~~^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\django\db\models\query.py", line 436, in __getitem__
    return qs._result_cache[0]
           ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2025-09-27 16:28:39,447 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-27 16:28:46,649 -User: jason21 - Path: /messages/
2025-09-27 16:28:46,772 -Internal Server Error: /messages/
Traceback (most recent call last):
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py", line 53, in __call__
    fith_message = messages[4]
                   ~~~~~~~~^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\django\db\models\query.py", line 436, in __getitem__
    return qs._result_cache[0]
           ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2025-09-27 16:29:09,197 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-27 16:29:33,573 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\messaging_app\settings.py changed, reloading.
2025-09-27 16:29:37,347 -User: jason21 - Path: /messages/
2025-09-27 17:17:42,278 -User: jason21 - Path: /messages/
2025-09-27 17:18:16,720 -User: jason21 - Path: /messages/
2025-09-28 07:41:45,307 -User: jason21 - Path: /
2025-09-28 07:41:47,337 -User: jason21 - Path: /
2025-09-28 07:41:57,753 -User: jason21 - Path: /favicon.ico
2025-09-28 07:41:58,279 -Not Found: /favicon.ico
2025-09-28 07:43:05,812 -User: jason21 - Path: /messages/
2025-09-28 07:46:22,325 -User: jason21 - Path: /messages/
2025-09-28 07:47:55,919 -User: jason21 - Path: /
2025-09-28 07:48:10,932 -User: jason21 - Path: /
2025-09-28 07:48:16,866 -User: jason21 - Path: /messages/
2025-09-28 07:49:40,496 -User: jason21 - Path: /conversation/
2025-09-28 07:49:50,072 -User: jason21 - Path: /messages/
2025-09-28 07:50:08,043 -User: jason21 - Path: /
2025-09-28 07:50:38,454 -User: jason21 - Path: /messages/
2025-09-28 07:51:17,825 -User: Anonymous - Path: /
2025-09-28 07:51:17,839 -Unauthorized: /
2025-09-28 07:51:24,539 -User: Anonymous - Path: /favicon.ico
2025-09-28 07:51:24,554 -Not Found: /favicon.ico
2025-09-28 07:51:28,037 -User: Anonymous - Path: /api-auth/login/
2025-09-28 07:51:47,787 -User: jason21 - Path: /api-auth/logout/
2025-09-28 07:51:47,823 -User: Anonymous - Path: /messages/
2025-09-28 07:51:47,834 -Unauthorized: /messages/
2025-09-28 07:51:50,596 -User: Anonymous - Path: /api-auth/login/
2025-09-28 07:52:48,888 -User: Anonymous - Path: /api-auth/login/
2025-09-28 07:54:31,824 -User: Anonymous - Path: /api-auth/login/
2025-09-28 07:54:34,649 -User: jason21 - Path: /
2025-09-28 07:54:38,666 -User: jason21 - Path: /messages/
2025-09-28 07:55:34,505 -User: jason21 - Path: /conversation/
2025-09-28 07:55:52,433 -User: jason21 - Path: /admin
2025-09-28 07:55:52,482 -User: jason21 - Path: /admin/
2025-09-28 07:55:52,516 -User: jason21 - Path: /admin/login/
2025-09-28 08:03:28,854 -User: Anonymous - Path: /
2025-09-28 08:03:29,054 -Unauthorized: /
2025-09-28 08:04:02,389 -User: Anonymous - Path: /messages/
2025-09-28 08:04:02,407 -Unauthorized: /messages/
2025-09-28 08:04:29,636 -User: jason21 - Path: /admin/login/
2025-09-28 08:04:29,662 -User: Anonymous - Path: /
2025-09-28 08:04:29,668 -Unauthorized: /
2025-09-28 08:04:35,806 -User: Anonymous - Path: /api-auth/login/
2025-09-28 08:04:41,555 -User: Anonymous - Path: /api-auth/login/
2025-09-28 08:04:45,248 -User: jason21 - Path: /
2025-09-28 08:04:50,030 -User: jason21 - Path: /messages/
2025-09-28 08:09:38,174 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\models.py changed, reloading.
2025-09-28 08:09:52,028 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\models.py changed, reloading.
2025-09-28 08:10:09,291 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\models.py changed, reloading.
2025-09-28 08:11:29,555 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\views.py changed, reloading.
2025-09-28 08:15:26,891 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\views.py changed, reloading.
2025-09-28 08:19:44,627 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\serializers.py changed, reloading.
2025-09-28 08:22:22,227 -User: jason21 - Path: /messages/
2025-09-28 08:26:14,676 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\models.py changed, reloading.
2025-09-28 08:26:48,138 -User: jason21 - Path: /messages/
2025-09-28 08:27:40,125 -User: jason21 - Path: /messages/
2025-09-28 08:28:33,852 -User: jason21 - Path: /messages/
2025-09-28 15:32:36,235 -User: jason21 - Path: /
2025-09-28 15:32:40,202 -User: jason21 - Path: /messages/
2025-09-28 15:33:18,544 -User: jason21 - Path: /messages/
2025-09-28 15:33:18,612 -Forbidden: /messages/
2025-09-28 15:33:40,951 -User: jason21 - Path: /messages/
2025-09-28 15:34:16,498 -User: jason21 - Path: /messages/
2025-09-28 15:34:38,077 -User: jason21 - Path: /messages/
2025-09-28 15:34:59,924 -User: jason21 - Path: /messages/
2025-09-28 15:36:21,414 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\messaging_app\settings.py changed, reloading.
2025-09-28 15:36:50,699 -User: jason21 - Path: /
2025-09-28 15:36:53,705 -User: jason21 - Path: /messages/
2025-09-28 15:36:54,017 -Internal Server Error: /messages/
Traceback (most recent call last):
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py", line 62, in __call__
    current_time = timezone.now()
                   ^^^^^^^^^^^^
AttributeError: type object 'datetime.timezone' has no attribute 'now'
2025-09-28 15:37:38,783 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-28 15:38:04,177 -User: jason21 - Path: /admin/login/
2025-09-28 15:38:18,816 -User: jason21 - Path: /messages/
2025-09-28 15:38:18,908 -Internal Server Error: /messages/
Traceback (most recent call last):
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py", line 62, in __call__
    current_time = timezone.now
                   ^^^^^^^^^^^^
AttributeError: type object 'datetime.timezone' has no attribute 'now'
2025-09-28 15:38:47,268 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-28 15:38:58,507 -User: jason21 - Path: /messages/
2025-09-28 15:38:58,689 -Internal Server Error: /messages/
Traceback (most recent call last):
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py", line 63, in __call__
    time_range = current_time - fith_msg_sent_at
                 ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
TypeError: can't subtract offset-naive and offset-aware datetimes
2025-09-28 15:44:32,195 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-28 15:45:22,437 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-28 15:46:25,284 -User: jason21 - Path: /
2025-09-28 15:46:32,394 -User: jason21 - Path: /messages/
2025-09-28 15:46:32,532 -Internal Server Error: /messages/
Traceback (most recent call last):
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py", line 64, in __call__
    time_range_in_sec = time_range.timedelta.total_seconds()
                        ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'datetime.timedelta' object has no attribute 'timedelta'
2025-09-28 15:48:06,777 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-28 15:48:23,803 -User: jason21 - Path: /messages/
2025-09-28 15:48:23,840 -Forbidden: /messages/
2025-09-28 15:48:51,774 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-28 15:49:19,210 -User: jason21 - Path: /messages/
2025-09-28 15:49:19,283 -Forbidden: /messages/
2025-09-28 15:49:49,068 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-28 15:50:04,779 -User: jason21 - Path: /messages/
2025-09-28 15:50:04,900 -Forbidden: /messages/
2025-09-28 15:50:59,571 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-28 15:51:20,426 -User: jason21 - Path: /messages/
2025-09-28 15:51:20,590 -Forbidden: /messages/
2025-09-28 15:52:02,715 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-28 15:52:13,018 -User: jason21 - Path: /messages/
2025-09-28 15:52:13,307 -Internal Server Error: /messages/
Traceback (most recent call last):
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py", line 61, in __call__
    fith_msg_sent_at= messages[4].sent_at
                      ~~~~~~~~^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\django\db\models\query.py", line 436, in __getitem__
    return qs._result_cache[0]
           ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2025-09-28 15:54:29,941 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-28 15:54:48,622 -User: jason21 - Path: /messages/
2025-09-28 15:54:48,802 -Internal Server Error: /messages/
Traceback (most recent call last):
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py", line 60, in __call__
    messages = messages[-5:]
               ~~~~~~~~^^^^^
  File "C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\env\Lib\site-packages\django\db\models\query.py", line 415, in __getitem__
    raise ValueError("Negative indexing is not supported.")
ValueError: Negative indexing is not supported.
2025-09-28 15:56:53,782 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-28 15:57:07,390 -User: jason21 - Path: /messages/
2025-09-28 15:57:07,579 -Forbidden: /messages/
2025-09-28 15:57:36,084 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-28 15:57:47,142 -User: jason21 - Path: /messages/
2025-09-28 15:57:47,378 -Forbidden: /messages/
2025-09-28 15:58:10,551 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-28 16:03:18,199 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-28 16:04:20,343 -C:\Users\Elite Phrasium\OneDrive\Desktop\ALX\backend\week_4\alx-backend-python\Django-Middleware-0x03\chats\middleware.py changed, reloading.
2025-09-28 16:04:52,497 -User: jason21 - Path: /
2025-09-28 16:04:55,459 -User: jason21 - Path: /messages/
2025-09-28 16:05:16,251 -User: jason21 - Path: /messages/
